apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
  namespace: slack
data:
  .kubewatch.yaml: |
    handler:
      slack:
        token: KUBEWATCH_SLACK_TOKEN
        channel: KUBEWATCH_SLACK_CHANNEL
    resource:
      deployment: true
      replicationcontroller: true
      replicaset: true
      daemonset: true
      services: false
      pod: true
      secret: true
      configmap: true
      namespace: true



